version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres-cep-service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cep_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    ports:
      - "8082:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
volumes:
  postgres_data:
